//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.VirtualCare.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auth.VirtualCare.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Does not exist queues with combinations between place, city and service.
        /// </summary>
        public static string DoesNotExistQueueCombinations {
            get {
                return ResourceManager.GetString("DoesNotExistQueueCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dont possible the process creation.
        /// </summary>
        public static string DontPossibleProcessCreation {
            get {
                return ResourceManager.GetString("DontPossibleProcessCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error operation.
        /// </summary>
        public static string ErrorOperation {
            get {
                return ResourceManager.GetString("ErrorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information not found.
        /// </summary>
        public static string InformationNotFound {
            get {
                return ResourceManager.GetString("InformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient state must be ATTENTIONWAITING, user state must be AVAILABLE, and medical record state must be PENDING for assignment.
        /// </summary>
        public static string InvalidStateForAsignation {
            get {
                return ResourceManager.GetString("InvalidStateForAsignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient state must be ATTENTIONWAITING, ASSIGNED, or INPROCESS; user state must be ASSIGNED or INPROCESS; and medical record state must be ASSIGNED or INPROCESS for cancellation.
        /// </summary>
        public static string InvalidStateForCancel {
            get {
                return ResourceManager.GetString("InvalidStateForCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient state must be ATTENDED, CANCELLED, or EMPTY for creation.
        /// </summary>
        public static string InvalidStateForCreation {
            get {
                return ResourceManager.GetString("InvalidStateForCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient, user, and medical record states must all be INPROCESS for finalizationsuario y atención deben tener estado en proceso para finalizar..
        /// </summary>
        public static string InvalidStateForFinish {
            get {
                return ResourceManager.GetString("InvalidStateForFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient, user, and medical record states must all be ASSIGNED for starting the process.
        /// </summary>
        public static string InvalidStateForInProcess {
            get {
                return ResourceManager.GetString("InvalidStateForInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success Asignation.
        /// </summary>
        public static string SuccessAssignation {
            get {
                return ResourceManager.GetString("SuccessAssignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success creation attention.
        /// </summary>
        public static string SuccessCreation {
            get {
                return ResourceManager.GetString("SuccessCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success initiation attention.
        /// </summary>
        public static string SuccessInProcess {
            get {
                return ResourceManager.GetString("SuccessInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success Login.
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success operation.
        /// </summary>
        public static string SuccessOperation {
            get {
                return ResourceManager.GetString("SuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success cancellation attention.
        /// </summary>
        public static string SucessCancel {
            get {
                return ResourceManager.GetString("SucessCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success finalization success.
        /// </summary>
        public static string SucessFinish {
            get {
                return ResourceManager.GetString("SucessFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Code Service does not exist.
        /// </summary>
        public static string TheCodeServiceDoesNotExist {
            get {
                return ResourceManager.GetString("TheCodeServiceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The medical record does not exist.
        /// </summary>
        public static string TheMedicalRecordDoesNotExist {
            get {
                return ResourceManager.GetString("TheMedicalRecordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The patient does not exist.
        /// </summary>
        public static string ThePatientDoesNotExist {
            get {
                return ResourceManager.GetString("ThePatientDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The patient has an ongoing appointment.
        /// </summary>
        public static string ThePatientHasAnOngoingAttention {
            get {
                return ResourceManager.GetString("ThePatientHasAnOngoingAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user does not exist.
        /// </summary>
        public static string TheUserDoesNotExist {
            get {
                return ResourceManager.GetString("TheUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user does not related priority service.
        /// </summary>
        public static string TheUserDoesNotRelatedPriorityService {
            get {
                return ResourceManager.GetString("TheUserDoesNotRelatedPriorityService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid transaction.
        /// </summary>
        public static string TransitionInvalid {
            get {
                return ResourceManager.GetString("TransitionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transition is valid.
        /// </summary>
        public static string TransitionValid {
            get {
                return ResourceManager.GetString("TransitionValid", resourceCulture);
            }
        }
    }
}
